//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LavazemYadaki.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anbar
    {
        public Anbar()
        {
            this.Kala = new HashSet<Kala>();
        }
    
        public int AnbarId { get; set; }
        public string TitleAnbar { get; set; }
    
        public virtual ICollection<Kala> Kala { get; set; }
    }
}
