//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LavazemYadaki.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactorAnbar
    {
        public int FactorAnbarId { get; set; }
        public int KalaId { get; set; }
        public Nullable<int> Bestankar { get; set; }
        public Nullable<int> Bedehkar { get; set; }
        public Nullable<System.DateTime> Tarikh { get; set; }
        public int PersonId { get; set; }
    
        public virtual Kala Kala { get; set; }
        public virtual Person Person { get; set; }
    }
}
