//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LavazemYadaki.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kala
    {
        public Kala()
        {
            this.FactorAnbar = new HashSet<FactorAnbar>();
            this.FactorForoosh = new HashSet<FactorForoosh>();
        }
    
        public int KalaId { get; set; }
        public string TitleKala { get; set; }
        public string CodeKala { get; set; }
        public Nullable<int> OrderPoint { get; set; }
        public int AnbarId { get; set; }
    
        public virtual Anbar Anbar { get; set; }
        public virtual ICollection<FactorAnbar> FactorAnbar { get; set; }
        public virtual ICollection<FactorForoosh> FactorForoosh { get; set; }
    }
}
