//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LavazemYadaki.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LavazemYadakiEntities : DbContext
    {
        public LavazemYadakiEntities()
            : base("name=LavazemYadakiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Anbar> Anbar { get; set; }
        public DbSet<FactorAnbar> FactorAnbar { get; set; }
        public DbSet<FactorForoosh> FactorForoosh { get; set; }
        public DbSet<Kala> Kala { get; set; }
        public DbSet<Person> Person { get; set; }
    }
}
